logo: Olga <span>Panasenco</span>
title: Olga Panasenco
description: >
  Olga Panasenco's personal site and gallery
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "olga.panasen.co" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Olga Panasenco's Gallery
banner-desc: Art and Physics

# Author settings
author-pic: olga.png
author-name: Olga Panasenco
about-author: # about author
website: https://olga.panasen.co

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
